### PR TITLE
chore: add Node.js 10

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by dougwilson** [comment]
Thanks! Looks like it ran clean! Can you update the commit message to match the formatting from when we added to new major versions and run the minor version, please?

**Comment by DanielRuf** [comment]
> Thanks! Looks like it ran clean! Can you update the commit message to match the formatting from when we added to new major versions and run the minor version, please?

Sorry but I do not fully understand what you mean.

**Comment by dougwilson** [comment]
So we don't prefix any commits with "chore:" and introducing a new major version we call out in the commit message specially. Also should be "10.1" in travis instead of just "10" so we don't automatically pick up new minor versions until we can test them :+1:

**Comment by DanielRuf** [comment]
> So we don't prefix any commits with "chore:"

You do not have / use any commitlint? It eases many things.
How should the commit message look like? In sentence form?

**Comment by DanielRuf** [comment]
> So we don't prefix any commits with "chore:" and introducing a new major version we call out in the commit message specially.

It is just CI and does not affect anyony.

**Comment by dougwilson** [comment]
I can just make the commit :+1: it would take less time. You can always just have looked at the commit history to have seen it.

**Comment by dougwilson** [comment]
> It is just CI and does not affect anyony.

It breaks my scripts that generate the history.md file based on commit messages.

**Comment by DanielRuf** [comment]
Sorry but I could still rebase and merge.

> It breaks my scripts that generate the history.md file based on commit messages.

I was not aware of this. Is this a custom script?

**Comment by DanielRuf** [comment]
Mh, ok =(

**Comment by DanielRuf** [comment]
Also you could have pushed to my branch.

**Comment by dougwilson** [comment]
But at that point, I can just push to master?

**Comment by DanielRuf** [comment]
Whatever. The collaboration could have been better.

**Pull request closed without merging**
