### PR TITLE
Add option to skip compression

### PR DESCRIPTION
**Pull request by jonathanong**

### CODE REVIEW

**Comment by dougwilson** [comment]
I'm not really a fan of magic res properties. Can't you implement this using a custom filter?

**Comment by jonathanong** [comment]
ya i could. i'm just running into streaming problems with heroku and trying `res.flush()` first so i might not even need this.

**Comment by rlidwka** [comment]
I believe it could be done in custom middleware. Or include compression middleware only in routes that need it.

Extending `res` is a bad idea because of name collisions.

Also, it's kinda similar to https://github.com/strongloop/express/pull/2422

**Comment by dougwilson** [comment]
I'm closing your PR, with the official answer of the following ;)
```js
app.use(compression({filter: shouldCompress}))

function shouldCompress(req, res) {
  if (res.compress === false) {
    // don't compress responses with this magic flag
    return false
  }

  // fallback to standard filter function
  return compression.filter(req, res)
}
```

**Comment by jonathanong** [comment]
ya i was going to close it anyways. all i needed was the flush option. hahaha

**Comment by dougwilson** [comment]
:wc: :toilet:

**Pull request closed without merging**
