### PR TITLE
deps: bytes@3.1.2

### PR DESCRIPTION
**Pull request by bjohansebas**

### CODE REVIEW

**Comment by bjohansebas** [comment]
@UlisesGascon, maybe we can do a patch version in the meantime and then focus on 1.8?

**Review by UlisesGascon — APPROVED** [review]

**Comment by UlisesGascon** [comment]
Sure! Do you want me to include additional PRs in this patch?

**Comment by bjohansebas** [comment]
I don't think there are any PRs that can be included in this patch, all the other PRs change some functionality from what I've seen

**Comment by UlisesGascon** [comment]
I will prepare a release then :+1:

**Pull request merged**
