### PR TITLE
chore: clone last 5 commits

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by dougwilson** [comment]
I don't understand what this does and there is no description can you elaborate?

**Comment by DanielRuf** [comment]
By default Travis does a shallow clone with the last 50 commits. Cloning the last 5 is sufficient and often faster.

See https://docs.travis-ci.com/user/customizing-the-build#Git-Clone-Depth

**Comment by dougwilson** [comment]
So the docs seem to indicate that if we set it to 5 and then there were five builds in the queue it will ignore new pushes until there are less than the depth in the build queue? That seems bad because we can sometimes have more than five in queue when updating deps. I don't see that the build cor this commit for master took any less time?

**Comment by DanielRuf** [comment]
> five builds in the queue it will ignore new pushes until there are less than the depth in the build queue

No, not exactly. If there are builds with the same commits, then they are not directly triggered (one build per commit combination). It is about commits not builds.

> Please note that if you use a depth of 1 and have a queue of jobs, Travis CI won’t build commits that are in the queue when you push a new commit.

**Comment by DanielRuf** [comment]
https://travis-ci.org/expressjs/compression/jobs/380870884#L413
https://travis-ci.org/expressjs/compression/jobs/359185565#L415

But this higly depends on the diff sizes and actual changes.

**Comment by dougwilson** [comment]
Ok. Can we validate this before merging, please. The description is how I would interpret it. We can test by having a repo with depth = 5 then push, one by one so they trigger a build, 10 commits. All 10 should get built. If we can confirm that first, then sounds good to merge.

**Comment by DanielRuf** [comment]
> All 10 should get built.

They will be all built (afaik). Did not see anything contrary in big repos like magento/magento2 and others where I proposed the same changes.

**Comment by dougwilson** [comment]
That doesn't answer the question.

**Pull request closed without merging**
